*Write a Python program to find the maximum and minimum element in a tuple.*

In [ ]:
# Tuple max and min
numbers = (45, 22, 88, 33, 99, 11)
print("Tuple:", numbers)
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))


Tuple: (45, 22, 88, 33, 99, 11)
Maximum: 99
Minimum: 11


Write a Python program to create a class Student with attributes name and marks, and display their details.

*Given a tuple of elements, count the frequency of each element.*

In [4]:
tup = ('apple', 'banana', 'apple', 'orange', 'banana', 'apple')

freq = {}
for item in tup:
    freq[item] = freq.get(item, 0) + 1

print("Element frequencies:", freq)


Element frequencies: {'apple': 3, 'banana': 2, 'orange': 1}


In [2]:
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def display(self):
        print(f"Name: {self.name}, Marks: {self.marks}")

# Example usage
s1 = Student("Pavitra", 92)
s1.display()


Name: Pavitra, Marks: 92


*Create a Python class BankAccount that allows users to deposit, withdraw, and check balance. Ensure balance doesn’t go below zero.*

In [3]:
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited ₹{amount}. Current Balance: ₹{self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient balance!")
        else:
            self.balance -= amount
            print(f"Withdrawn ₹{amount}. Remaining Balance: ₹{self.balance}")

# Example
acc1 = BankAccount("Pavitra", 5000)
acc1.deposit(2000)
acc1.withdraw(1500)
acc1.withdraw(6000)


Deposited ₹2000. Current Balance: ₹7000
Withdrawn ₹1500. Remaining Balance: ₹5500
Insufficient balance!


**Perform matrix addition, subtraction, and transpose using NumPy.**

In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Transpose of A:\n", A.T)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[6 5 4]
 [3 2 1]]
Addition:
 [[7 7 7]
 [7 7 7]]
Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]
Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


*Create a Pandas DataFrame for students with columns (Name, Marks, Subject) and display the student with the highest marks.*

In [6]:
import pandas as pd

data = {
    'Name': ['Pavitra', 'Ravi', 'Sneha', 'Arjun'],
    'Marks': [92, 85, 96, 78],
    'Subject': ['Math', 'Science', 'English', 'Math']
}

df = pd.DataFrame(data)
print("Student Data:\n", df)
print("\nTop Scorer:\n", df.loc[df['Marks'].idxmax()])


Student Data:
       Name  Marks  Subject
0  Pavitra     92     Math
1     Ravi     85  Science
2    Sneha     96  English
3    Arjun     78     Math

Top Scorer:
 Name         Sneha
Marks           96
Subject    English
Name: 2, dtype: object


*Write a program that reads a text file and counts how many times each word appears.*

In [7]:
# Create and write sample file
with open("sample.txt", "w") as f:
    f.write("Python is fun and Python is powerful")

# Read and count words
with open("sample.txt", "r") as f:
    words = f.read().split()

word_count = {}
for w in words:
    word_count[w] = word_count.get(w, 0) + 1

print("Word Frequencies:", word_count)


Word Frequencies: {'Python': 2, 'is': 2, 'fun': 1, 'and': 1, 'powerful': 1}


*Write a program that takes two numbers from the user and handles division by zero using try-except*

In [8]:
try:
    a = int(input("Enter numerator: "))
    b = int(input("Enter denominator: "))
    result = a / b
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")
except ValueError:
    print("Error: Please enter valid numbers!")


Enter numerator: 22
Enter denominator: 2
Result: 11.0


*Write a Python class Library to add, remove, and display available books*

In [9]:
class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)
        print(f"✅ '{book}' added to library")

    def remove_book(self, book):
        if book in self.books:
            self.books.remove(book)
            print(f"❌ '{book}' removed")
        else:
            print("Book not found!")

    def display_books(self):
        print("\n📚 Available Books:")
        for b in self.books:
            print("-", b)

# Example
lib = Library()
lib.add_book("Python Basics")
lib.add_book("Data Science 101")
lib.display_books()
lib.remove_book("Python Basics")
lib.display_books()


✅ 'Python Basics' added to library
✅ 'Data Science 101' added to library

📚 Available Books:
- Python Basics
- Data Science 101
❌ 'Python Basics' removed

📚 Available Books:
- Data Science 101


*Merge two tuples and sort them in ascending order without converting to a list.*

In [10]:
t1 = (9, 1, 5, 2)
t2 = (8, 3, 7)
merged = tuple(sorted(t1 + t2))
print("Merged and Sorted Tuple:", merged)


Merged and Sorted Tuple: (1, 2, 3, 5, 7, 8, 9)


*Create a 2D NumPy array and find row-wise and column-wise sums and means.*

In [11]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("Array:\n", arr)
print("Row-wise Sum:", np.sum(arr, axis=1))
print("Column-wise Mean:", np.mean(arr, axis=0))


Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row-wise Sum: [ 60 150 240]
Column-wise Mean: [40. 50. 60.]


*Create a DataFrame of employees and display those who earn more than ₹50,000.*

In [12]:
import pandas as pd

data = {
    'Name': ['Anu', 'Pavitra', 'Ravi', 'Kiran', 'Sneha'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Admin'],
    'Salary': [48000, 67000, 52000, 45000, 80000]
}

df = pd.DataFrame(data)
print("All Employees:\n", df)

high_salary = df[df['Salary'] > 50000]
print("\n💰 Employees earning > ₹50,000:\n", high_salary)


All Employees:
       Name Department  Salary
0      Anu         HR   48000
1  Pavitra         IT   67000
2     Ravi    Finance   52000
3    Kiran         IT   45000
4    Sneha      Admin   80000

💰 Employees earning > ₹50,000:
       Name Department  Salary
1  Pavitra         IT   67000
2     Ravi    Finance   52000
4    Sneha      Admin   80000


*Write a program that counts lines, words, and characters in a text file*

In [13]:
with open("data.txt", "w") as f:
    f.write("Python is powerful.\nPython is easy to learn.\nKeep coding daily!")

lines = words = chars = 0
with open("data.txt", "r") as f:
    for line in f:
        lines += 1
        words += len(line.split())
        chars += len(line)

print(f"Lines: {lines}, Words: {words}, Characters: {chars}")


Lines: 3, Words: 11, Characters: 63


*Write a function to check whether a given string is a palindrome*

In [14]:
def is_palindrome(s):
    s = s.lower().replace(" ", "")
    return s == s[::-1]

text = input("Enter a string: ")
print("✅ Palindrome" if is_palindrome(text) else "❌ Not a palindrome")


Enter a string: 121
✅ Palindrome


*Write a program to safely access an element from a list by index*

In [15]:
try:
    lst = [10, 20, 30, 40]
    idx = int(input("Enter index to access: "))
    print("Element:", lst[idx])
except IndexError:
    print("Error: Index out of range!")
except ValueError:
    print("Error: Invalid input! Enter a number.")


Enter index to access: 1
Element: 20


*Generate random marks using NumPy and analyze with Pandas*

In [16]:
import numpy as np
import pandas as pd

names = ['Pavitra', 'Ravi', 'Sneha', 'Kiran', 'Anu']
marks = np.random.randint(50, 100, size=5)

df = pd.DataFrame({'Name': names, 'Marks': marks})
print(df)

print("\nAverage Marks:", df['Marks'].mean())
print("Top Scorer:\n", df.loc[df['Marks'].idxmax()])


      Name  Marks
0  Pavitra     69
1     Ravi     56
2    Sneha     98
3    Kiran     67
4      Anu     54

Average Marks: 68.8
Top Scorer:
 Name     Sneha
Marks       98
Name: 2, dtype: object


*Use map, filter, and lambda to process a list of numbers*

In [17]:
nums = [10, 25, 33, 50, 77, 82]

# Double each number
doubled = list(map(lambda x: x * 2, nums))

# Filter even numbers
even = list(filter(lambda x: x % 2 == 0, nums))

print("Original:", nums)
print("Doubled:", doubled)
print("Even Numbers:", even)


Original: [10, 25, 33, 50, 77, 82]
Doubled: [20, 50, 66, 100, 154, 164]
Even Numbers: [10, 50, 82]


*Design an OOP-based calculator that performs +, -, , / operations*

In [18]:
class Calculator:
    def add(self, a, b): return a + b
    def sub(self, a, b): return a - b
    def mul(self, a, b): return a * b
    def div(self, a, b):
        try:
            return a / b
        except ZeroDivisionError:
            return "Cannot divide by zero!"

calc = Calculator()
print("Addition:", calc.add(10, 5))
print("Subtraction:", calc.sub(10, 5))
print("Multiplication:", calc.mul(10, 5))
print("Division:", calc.div(10, 0))


Addition: 15
Subtraction: 5
Multiplication: 50
Division: Cannot divide by zero!
